--
-- 视频
--
CREATE TABLE video (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `videoName` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '视频名称',
  `linkURL` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '视频地址',
  `des` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '描述',
  `ownerID` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建人ID',
  `ownerName` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '创建人姓名',
  `deleteStatus` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '软删除: 0未删除，1删除',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARACTER SET=utf8 COMMENT='视频';